apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: brext
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/brext
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "brext",
    "plugins": [
      {
        "type": "cnv-bridge",
        "bridge": "brext",
          "ipam": {
            "type": "whereabouts",
            "range": "172.22.0.0/24",
            "exclude": [
            "172.22.0.1/32",
            "172.22.0.2/32",
            "172.22.0.3/32",
            "172.22.0.100/32",
            "172.22.0.101/32",
            "172.22.0.102/32",
            "172.22.0.200/32",
            "172.22.0.201/32",
            "172.22.0.202/32"
            ],
            "gateway": "172.22.0.1"
        }
      },
      {
        "type": "tuning"
      }
    ]
  }'
